name: Playwright Gpos

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
  - cron: '0 13 * * *' # Running otomatis jam 20:00 WIB
  workflow_dispatch:


permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm

    - name: Install dependencies
      run: npm ci

    - name: Get Playwright version
      run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('@playwright/test/package.json').version)")" >> $GITHUB_ENV

    - name: Cache Playwright Browsers
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      id: playwright_tests
      run: npx bddgen && npx playwright test
      continue-on-error: true

    - name: Upload Allure Results as Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: raw-allure-results
        path: allure-results/
        retention-days: 7

    - name: Get Allure history
      if: always()
      continue-on-error: true
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: allure-history

    - name: Generate Allure Report
